[package]
name = "yarrow_runtime"
version = "0.1.0"
authors = ["Shoeboxam <shoeboxam@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.5.0"
bytes = "0.4.12"
libc = "0.2"
byteorder = "1.3.2"
probability = "0.17.0"
openssl = "0.10.25"
num = "0.2.0"
csv = "1.1.1"
ndarray = "0.13.0"
ndarray-stats = "0.3.0"
ffi-support = "0.3.5"
ieee754 = "0.2"
itertools = "0.8.2"
itertools-num = "0.1.3"
yarrow_validator = {path = "../validator-rust"}

[build-dependencies]
prost-build = "0.5.0"
cbindgen = "0.9.1"

[lib]
name = "yarrow_runtime"
crate-type = ["cdylib"]

[profile.release]
debug = true